from py2ts.builder import TSBuilder
from py2ts.config import CONFIG

from beets_flask.config.schema import BeetsSchema
from beets_flask.disk import Archive, File, FileSystemItem, Folder
from beets_flask.importer.session import CandidateChoiceFallback
from beets_flask.importer.states import (
    SerializedSessionState,
)
from beets_flask.invoker import EnqueueKind
from beets_flask.invoker.enqueue import (
    Search,
)
from beets_flask.server.routes.db_models.session import MinimalSession
from beets_flask.server.routes.inbox import InboxStats
from beets_flask.server.routes.library.stats import LibraryStats
from beets_flask.server.routes_next.beets._types import (
    AlbumSortField,
    ArtistSortField,
    BulkResult,
    ItemSortField,
    MultiAlbumDocument,
    MultiArtistDocument,
    MultiItemDocument,
    SingleAlbumDocument,
    SingleArtistDocument,
    SingleItemDocument,
)
from beets_flask.server.websocket.status import (
    FileSystemUpdate,
    FolderStatusUpdate,
    JobStatusUpdate,
)

prefix = """/*
 * This file is generated by ../backend/generate_types.py
 * Do not edit this file manually!
 */
"""

CONFIG.any_as_unknown = True
CONFIG.indent_with_tabs = False
CONFIG.indent_size = 4

builder = TSBuilder()


# Session state
builder.add(SerializedSessionState)

# Best-match chip info per folder
builder.add(MinimalSession)

# ------------------------------- inbox routes ------------------------------- #

# Folder
builder.add(FileSystemItem)
builder.add(File)
builder.add(Archive)
builder.add(Folder)
builder.add(InboxStats)


# Invoker / enqueue
builder.add(EnqueueKind)
builder.add(Search)
builder.add(CandidateChoiceFallback)


# ------------------------------ library routes ------------------------------ #

# Stats
builder.add(LibraryStats)

# Beets api resources (json:api subset, see routes_next/beets).
# py2ts resolves referenced types, so adding the documents also generates
# their resources/attributes (e.g. SingleItemDocument -> ItemResource).
builder.add(ItemSortField)
builder.add(AlbumSortField)
builder.add(ArtistSortField)
builder.add(BulkResult)
builder.add(SingleItemDocument)
builder.add(MultiItemDocument)
builder.add(SingleAlbumDocument)
builder.add(MultiAlbumDocument)
builder.add(SingleArtistDocument)
builder.add(MultiArtistDocument)


# ------------------------------ Status updates ------------------------------ #

builder.add(FolderStatusUpdate)
builder.add(JobStatusUpdate)
builder.add(FileSystemUpdate)


# ---------------------------------- Config ---------------------------------- #

builder.add(BeetsSchema)

builder.save_file("../frontend/src/pythonTypes.ts")
print("✅ Typescript types generated successfully!")
