# Workaround for Python 3.14 (PEP 649): class annotations are resolved lazily
# and no longer live in ``cls.__dict__``, so py2ts cannot see them. Resolve
# the hints ourselves and filter by ``cls.__annotations__`` instead.
from py2ts import generate as py2ts_generate  # noqa: E402
from py2ts.builder import TSBuilder
from py2ts.config import CONFIG


def _get_type_hints_no_inheritance(cls):
    from typing import get_type_hints

    all_hints = get_type_hints(cls, include_extras=True)
    cls_annotations = getattr(cls, "__annotations__", {}) or {}
    return {k: v for k, v in all_hints.items() if k in cls_annotations}


py2ts_generate._get_type_hints_no_inheritance = _get_type_hints_no_inheritance

from beets_flask.disk import Archive, File, FileSystemItem, Folder
from beets_flask.importer.session import CandidateChoiceFallback
from beets_flask.importer.states import (
    SerializedSessionState,
)
from beets_flask.invoker import EnqueueKind
from beets_flask.invoker.enqueue import (
    Search,
)
from beets_flask.server.routes.inbox import InboxStats
from beets_flask.server.routes.library.resources import (
    AlbumResponse,
    AlbumResponseExpanded,
    AlbumResponseMinimal,
    AlbumResponseMinimalExpanded,
    ItemResponse,
    ItemResponseMinimal,
)
from beets_flask.server.routes.library.stats import LibraryStats
from beets_flask.server.routes.musicbrainz.prepare import (
    ChecklistItem,
    PreparedRelease,
    PreparedTrack,
    ReleaseData,
    ReleaseFlags,
)
from beets_flask.server.websocket.status import (
    FileSystemUpdate,
    FolderStatusUpdate,
    JobStatusUpdate,
)

prefix = """/*
 * This file is generated by ../backend/generate_types.py
 * Do not edit this file manually!
 */
"""

CONFIG.any_as_unknown = True
CONFIG.indent_with_tabs = False
CONFIG.indent_size = 4

builder = TSBuilder()


# Session state
builder.add(SerializedSessionState)

# ------------------------------- inbox routes ------------------------------- #

# Folder
builder.add(FileSystemItem)
builder.add(File)
builder.add(Archive)
builder.add(Folder)
builder.add(InboxStats)


# Invoker / enqueue
builder.add(EnqueueKind)
builder.add(Search)
builder.add(CandidateChoiceFallback)


# ------------------------------ library routes ------------------------------ #

# Stats
builder.add(LibraryStats)

# Item responses
builder.add(ItemResponse)
builder.add(ItemResponseMinimal)

# Album responses
builder.add(AlbumResponse)
builder.add(AlbumResponseMinimal)
builder.add(AlbumResponseExpanded)
builder.add(AlbumResponseMinimalExpanded)

# ----------------------------- musicbrainz routes ---------------------------- #

builder.add(PreparedRelease)
builder.add(ReleaseData)
builder.add(PreparedTrack)
builder.add(ReleaseFlags)
builder.add(ChecklistItem)

# ------------------------------ Status updates ------------------------------ #

builder.add(FolderStatusUpdate)
builder.add(JobStatusUpdate)
builder.add(FileSystemUpdate)


builder.save_file("../frontend/src/pythonTypes.ts")
print("✅ Typescript types generated successfully!")
