"""initial

Revision ID: a986c03d9ba3
Revises:
Create Date: 2026-04-08 18:46:00.556681

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a986c03d9ba3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    import beets_flask.database.models.types

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "folder",
        sa.Column("full_path", sa.String(), nullable=False),
        sa.Column("is_album", sa.Boolean(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("full_path", "id"),
    )
    op.create_index(
        op.f("ix_folder_created_at"), "folder", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_folder_full_path"), "folder", ["full_path"], unique=False)
    op.create_table(
        "session",
        sa.Column("folder_hash", sa.String(), nullable=False),
        sa.Column("folder_revision", sa.Integer(), nullable=False),
        sa.Column(
            "progress",
            sa.Enum(
                "NOT_STARTED",
                "READING_FILES",
                "GROUPING_ALBUMS",
                "LOOKING_UP_CANDIDATES",
                "IDENTIFYING_DUPLICATES",
                "PREVIEW_COMPLETED",
                "DELETION_COMPLETED",
                "OFFERING_MATCHES",
                "MATCH_THRESHOLD",
                "WAITING_FOR_USER_SELECTION",
                "EARLY_IMPORTING",
                "IMPORTING",
                "MANIPULATING_FILES",
                "IMPORT_COMPLETED",
                "DELETING",
                name="progress",
            ),
            nullable=False,
        ),
        sa.Column("exc", sa.LargeBinary(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["folder_hash"],
            ["folder.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "folder_hash", "folder_revision", name="uq_folder_hash_revision"
        ),
    )
    op.create_index(
        op.f("ix_session_created_at"), "session", ["created_at"], unique=False
    )
    op.create_table(
        "task",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("chosen_candidate_id", sa.String(), nullable=True),
        sa.Column("toppath", sa.LargeBinary(), nullable=True),
        sa.Column("paths", sa.LargeBinary(), nullable=False),
        sa.Column("old_paths", sa.LargeBinary(), nullable=True),
        sa.Column("items", sa.LargeBinary(), nullable=False),
        sa.Column(
            "choice_flag",
            sa.Enum(
                "SKIP", "ASIS", "TRACKS", "APPLY", "ALBUMS", "RETAG", name="action"
            ),
            nullable=True,
        ),
        sa.Column("cur_artist", sa.String(), nullable=True),
        sa.Column("cur_album", sa.String(), nullable=True),
        sa.Column(
            "progress",
            sa.Enum(
                "NOT_STARTED",
                "READING_FILES",
                "GROUPING_ALBUMS",
                "LOOKING_UP_CANDIDATES",
                "IDENTIFYING_DUPLICATES",
                "PREVIEW_COMPLETED",
                "DELETION_COMPLETED",
                "OFFERING_MATCHES",
                "MATCH_THRESHOLD",
                "WAITING_FOR_USER_SELECTION",
                "EARLY_IMPORTING",
                "IMPORTING",
                "MANIPULATING_FILES",
                "IMPORT_COMPLETED",
                "DELETING",
                name="progress",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chosen_candidate_id"], ["candidate.id"], use_alter=True
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_created_at"), "task", ["created_at"], unique=False)
    op.create_table(
        "candidate",
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("match", sa.LargeBinary(), nullable=False),
        sa.Column("duplicate_ids", sa.String(), nullable=False),
        sa.Column(
            "mapping", beets_flask.database.models.types.IntDictType(), nullable=False
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_candidate_created_at"), "candidate", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_candidate_created_at"), table_name="candidate")
    op.drop_table("candidate")
    op.drop_index(op.f("ix_task_created_at"), table_name="task")
    op.drop_table("task")
    op.drop_index(op.f("ix_session_created_at"), table_name="session")
    op.drop_table("session")
    op.drop_index(op.f("ix_folder_full_path"), table_name="folder")
    op.drop_index(op.f("ix_folder_created_at"), table_name="folder")
    op.drop_table("folder")
    # ### end Alembic commands ###
