/*
 * This file is automatically generated by py2ts!
 * For more information, see:
 * https://github.com/semohr/py2ts
 */
export type SingleItemDocument = SingleResourceDocument<ItemResource>;

export type SingleArtistDocument = SingleResourceDocument<ArtistResource>;

export type SingleAlbumDocument = SingleResourceDocumentWithIncluded<
    AlbumResource,
    ItemResource
>;

export type MultiItemDocument = MultiResourceDocument<ItemResource>;

export type MultiArtistDocument = MultiResourceDocument<ArtistResource>;

export type MultiAlbumDocument = MultiResourceDocumentWithIncluded<
    AlbumResource,
    ItemResource
>;

export type ItemResource = Resource<ItemAttributes, 'item'>;

export type File = FileSystemItem;

export type ArtistResource = Resource<ArtistAttributes, 'artist'>;

export type AlbumResource = RelResource<AlbumAttributes, 'album', 'item'>;

export interface SingleResourceDocumentWithIncluded<
    R extends Resource = Resource,
    R_I extends Resource = Resource,
> extends SingleResourceDocument<R> {
    included: Array<R_I> | null;
}

export interface SingleResourceDocument<R extends Resource = Resource> {
    data: R;
    links: LinkObject;
    meta: MetaObject | null;
}

export interface SerializedSessionState {
    id: string;
    created_at: Date;
    updated_at: Date;
    folder_path: string;
    folder_hash: string;
    tasks: Array<SerializedTaskState>;
    status: SerializedProgressState;
    exc?: SerializedException | null;
}

export interface SerializedProgressState {
    progress: Progress;
    message: null | string;
    plugin_name: null | string;
}

export interface Search {
    search_ids: Array<string>;
    search_artist: null | string;
    search_name: null | string;
}

export interface ResourceIdentifier<T extends string = string> {
    type: T;
    id: string;
}

export interface Resource<A = unknown, T extends string = string> {
    type: T;
    id: string;
    attributes: A;
}

export interface RelResource<
    A = unknown,
    T extends string = string,
    T_I extends string = string,
> extends Resource<A, T> {
    relationships: Array<ResourceIdentifier<T_I>>;
}

export interface MusicInfo {
    type: 'album' | 'item' | 'track';
    artist: null | string;
    album: null | string;
    data_url: null | string;
    data_source: null | string;
    year: null | number;
    genres: Array<string> | null;
    media: null | string;
}

export interface MultiResourceDocumentWithIncluded<
    R extends Resource = Resource,
    R_I extends Resource = Resource,
> extends MultiResourceDocument<R> {
    included: Array<R_I> | null;
}

export interface MultiResourceDocument<R extends Resource = Resource> {
    data: Array<R>;
    links: LinkObject;
    meta: MetaObject | null;
}

export interface MinimalSession {
    session_id: string;
    folder_hash: string;
    best_candidate: MinimalBestCandidateInfo;
}

export interface MinimalBestCandidateInfo {
    data_source: string;
    distance: number;
    duplicates: Array<number>;
}

export interface LinkObject {
    self: string;
    next: null | string;
}

export interface LibraryStats {
    libraryPath: string;
    items: number;
    albums: number;
    artists: number;
    genres: number;
    labels: number;
    size: number;
    lastItemAdded: null | number;
    lastItemModified: null | number;
    runtime: number;
}

export interface JobStatusUpdate {
    message: string;
    num_jobs: number;
    job_metas: Array<JobMeta>;
    exc: SerializedException | null;
    event: 'job_status_update';
}

export interface ItemAttributes {
    title: null | string;
    artist: null | string;
}

export interface InboxStats {
    name: string;
    path: string;
    tagged_via_gui: number;
    imported_via_gui: number;
    size: number;
    nFiles: number;
    last_created: Date | null;
}

export interface FolderStatusUpdate {
    path: string;
    hash: string;
    status: FolderStatus;
    exc: SerializedException | null;
    event: 'folder_status_update';
}

export interface Folder extends FileSystemItem {
    children: Array<FileSystemItem>;
}

export interface FileSystemUpdate {
    exc: SerializedException | null;
    event: 'file_system_update';
}

export interface BulkResult {
    meta: MetaObject;
}

export interface MatchSectionSchema {
    strong_rec_thresh: number;
    medium_rec_thresh: number;
}

export interface ImportDuplicateKeys {
    album: Array<string> | string;
    item: Array<string> | string;
}

export interface ImportSection {
    duplicate_action: 'ask' | 'keep' | 'merge' | 'remove' | 'skip';
    move: 'False';
    copy: 'True';
    duplicate_keys: ImportDuplicateKeys;
}

export interface BeetsSchema {
    gui: BeetsFlaskSchema;
    directory: string;
    ignore: Array<string>;
    plugins: Array<string>;
    import_: ImportSection;
    match: MatchSectionSchema;
}

export interface TerminalSectionSchema {
    enabled: boolean;
    start_path: string;
}

export interface LibrarySectionSchema {
    readonly: boolean;
    artist_separators: Array<string>;
}

export interface InboxSectionSchema {
    ignore: '_use_beets_ignore' | Array<string>;
    debounce_before_autotag: number;
    temp_dir: string;
    folders: Record<string, InboxFolderSchema>;
}

export interface BeetsFlaskSchema {
    inbox: InboxSectionSchema;
    library: LibrarySectionSchema;
    terminal: TerminalSectionSchema;
    num_preview_workers: number;
}

export interface ArtistAttributes {
    artist: string;
    album_count: number;
    item_count: number;
    first_item_added: Date | null;
    last_item_added: Date | null;
    first_album_added: Date | null;
    last_album_added: Date | null;
}

export interface Archive extends FileSystemItem {
    is_album: boolean;
}

export interface AlbumAttributes {
    album: null | string;
    albumartist: null | string;
    year: null | number;
}

export enum Progress {
    NOT_STARTED = 0,
    READING_FILES = 10,
    GROUPING_ALBUMS = 11,
    LOOKING_UP_CANDIDATES = 12,
    IDENTIFYING_DUPLICATES = 13,
    PREVIEW_COMPLETED = 20,
    DELETION_COMPLETED = 21,
    OFFERING_MATCHES = 30,
    MATCH_THRESHOLD = 31,
    WAITING_FOR_USER_SELECTION = 32,
    EARLY_IMPORTING = 33,
    IMPORTING = 34,
    MANIPULATING_FILES = 35,
    IMPORT_COMPLETED = 40,
    DELETING = 50,
}

export enum ItemSortField {
    ADDED = 'added',
    YEAR = 'year',
    TITLE = 'title',
    ARTIST = 'artist',
    ALBUMARTIST = 'albumartist',
    ALBUM = 'album',
    TRACK = 'track',
    DISC = 'disc',
    LENGTH = 'length',
    BITRATE = 'bitrate',
}

export enum FolderStatus {
    UNKNOWN = -2,
    FAILED = -1,
    NOT_STARTED = 0,
    PENDING = 1,
    PREVIEWING = 2,
    PREVIEWED = 3,
    IMPORTING = 4,
    IMPORTED = 5,
    DELETING = 6,
    DELETED = 7,
}

export enum EnqueueKind {
    PREVIEW = 'preview',
    PREVIEW_ADD_CANDIDATES = 'preview_add_candidates',
    IMPORT_CANDIDATE = 'import_candidate',
    IMPORT_AUTO = 'import_auto',
    IMPORT_UNDO = 'import_undo',
    IMPORT_BOOTLEG = 'import_bootleg',
    _AUTO_IMPORT = '_auto_import',
    _AUTO_PREVIEW = '_auto_preview',
}

export enum CandidateChoiceFallback {
    ASIS = 1,
    BEST = 2,
}

export enum ArtistSortField {
    ARTIST = 'artist',
    ALBUM_COUNT = 'album_count',
    ITEM_COUNT = 'item_count',
}

export enum AlbumSortField {
    ADDED = 'added',
    ALBUM = 'album',
    ALBUMARTIST = 'albumartist',
    YEAR = 'year',
}

export interface SerializedException {
    type: string;
    message: string;
    description?: null | string;
    trace?: null | string;
}

export interface InboxFolderSchema {
    path: string;
    name: string;
    auto_threshold: null | number;
    autotag: 'auto' | 'bootleg' | 'off' | 'preview';
}

export interface MetaObject {
    total: number;
}

export interface Metadata {
    artist: null | string;
    album: null | string;
    albumartist: null | string;
    year: null | string;
    disctotal: null | string;
    mb_albumid: null | string;
    label: null | string;
    barcode: null | string;
    catalognum: null | string;
    country: null | string;
    media: null | string;
    albumdisambig: null | string;
}

export interface SerializedTaskState {
    id: string;
    created_at: Date;
    updated_at: Date;
    items: Array<ItemInfo>;
    current_metadata: Metadata;
    candidates: Array<SerializedCandidateState>;
    asis_candidate: SerializedCandidateState;
    duplicate_action: null | string;
    chosen_candidate_id: null | string;
    completed: boolean;
    toppath: null | string;
    paths: Array<string>;
}

export interface SerializedCandidateState {
    id: string;
    created_at: Date;
    updated_at: Date;
    duplicate_ids: Array<string>;
    type: string;
    penalties: Array<string>;
    distance: number;
    info: AlbumInfo | ItemInfo | TrackInfo;
    mapping: Record<number, number>;
    tracks: Array<TrackInfo>;
}

export interface JobMeta {
    folder_hash: string;
    folder_path: string;
    job_id: string;
    job_kind: string;
    job_frontend_ref?: null | string;
}

export interface ItemInfo extends MusicInfo {
    title: null | string;
    length: null | number;
    isrc: null | string;
    index: null | number;
    path: null | string;
    bitrate: null | number;
    format: null | string;
}

export interface FileSystemItem {
    type: 'archive' | 'directory' | 'file';
    full_path: string;
    hash: string;
    is_album: boolean;
}

export interface TrackInfo extends MusicInfo {
    title: null | string;
    length: null | number;
    isrc: null | string;
    index: null | number;
    medium_index: null | number;
    medium: null | number;
}

export interface AlbumInfo extends MusicInfo {
    mediums: null | number;
    country: null | string;
    label: null | string;
    catalognum: null | string;
    albumdisambig: null | string;
}
